#!/usr/bin/env bash
# release.sh
# Commit current changes, create an annotated tag, and push everything.
#
# Usage:
#   ./release.sh <new_tag> ["optional commit message"]
#
# Examples:
#   ./release.sh GANv2.1
#   ./release.sh GANv2.1 "Fix dataset loader and update report"
#
# Behavior:
#   - Stages all changes (git add -A).
#   - If there are staged changes, commits them. Commit message defaults to
#     "<tag>: <auto-generated short summary>" if you don't pass one.
#   - Creates an annotated tag <new_tag> on HEAD (fails if tag already exists).
#   - Pushes current branch + the new tag to origin.

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <new_tag> [commit message]"
  exit 1
fi

TAG="$1"
shift
MSG="${*:-}"

# Sanity: must be inside a git repo.
git rev-parse --show-toplevel >/dev/null

# Sanity: tag must not already exist locally or on remote.
if git rev-parse "$TAG" >/dev/null 2>&1; then
  echo "ERROR: Tag '$TAG' already exists locally."
  exit 1
fi
if git ls-remote --tags origin "refs/tags/$TAG" | grep -q .; then
  echo "ERROR: Tag '$TAG' already exists on origin."
  exit 1
fi

BRANCH="$(git branch --show-current)"
if [[ -z "$BRANCH" ]]; then
  echo "ERROR: Detached HEAD. Check out a branch first."
  exit 1
fi

echo "==> Repo:    $(git rev-parse --show-toplevel)"
echo "==> Branch:  $BRANCH"
echo "==> New tag: $TAG"
echo

echo "==> Staging all changes"
git add -A

if git diff --cached --quiet; then
  echo "==> No staged changes; tagging current HEAD as-is."
else
  if [[ -z "$MSG" ]]; then
    # Auto-summary: count of changed files.
    N=$(git diff --cached --name-only | wc -l | tr -d ' ')
    MSG="$TAG: update $N files"
  fi
  echo "==> Committing: $MSG"
  git commit -m "$MSG"
fi

echo
echo "==> Creating annotated tag $TAG"
git tag -a "$TAG" -m "$TAG"

echo
echo "==> Pushing branch $BRANCH"
git push origin "$BRANCH"

echo
echo "==> Pushing tag $TAG"
git push origin "$TAG"

echo
echo "==> Done."
git log --oneline -3
echo
echo "Remote refs:"
git ls-remote origin "refs/heads/$BRANCH" "refs/tags/$TAG"
